travis:
  secure:
    BINSTAR_TOKEN: ZOaplsuyXrLckLbOvFmmRiEReWmiTYcT08jjxULt258kgxYsddxiblvRbsGpa9wu27cSq8dxpWQNC11gPgn+G52bsCUnsKpPjz6r9flFofTzSl1fnW4Ee4pqLP0oGsDASoBNFSXgQLqhrfpiN7md+msuXUyhbK3YueQk3QQwswpcY38zA8Srs3Oj6veL0FfNGjQEwW8le79Z2OPL+7BBXM40C0lxiIsZFXUMSaEAxyOFTzWuA4n5SN0p4yHfeSO2rqiBFCcdFJujR4LZ7Lq0DFTsBWGJMpE4LpNoYCv/6mJslAR3pMauSTBPqq9tpX5Zk4Hb/HJDaB0U8bjAw8Pn9WxIOjeguYjbEQFhNegpVxu2N2Mq7CAHYF32qLJrlOIKfM26tNT8nNOLcbGLsTeAkV2iH/lYYZ/XmgX9Q+ggQFkXxdndwzAyonVi1ctGAUfT+PzRY0SkXfTYTNcYXtVwavpQM9IW8pFU5IrCcEyrSEBufCLM/yhz8hFQe4a0rFDfR4gfvxU/PgOfL9/9Bwg3s1OqJbWF8Z2fv0EYkET8DX/fy7RX3z0lA6t35zWPHNHSdTJAdw5TBd5rq1oxn2pJwqt+PjVM0chtWRB1g5eSdLA06nL8j03LFDjMjsd8tHZ2fsnxnGmoMwBQlL39hnH/ADG28Sr2Wevb3Kw/rK/rGOQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
