appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OuOkWRK2TaVdZLPJvZ2tADFvkCQEieg2blMadyk2fEZvDHvCs0v7MMmJd/AtFUve8hKcH5GPZF8rmsVi/jvw9kUKnXsCp9ozfbZHsYSUZSTEZmCzUgrFwed8JrhxWM3iWc52aQcbQbUcGecTy5av9/mXOIWOovjMwEGHNqMY2fqVRjbLq4g1n4jvYHv0g5ebDFRPzHhu9FF6uwKb4Q7DDxyjCymi56bSCRsts2TRx25bLFCoAN//P8aXBAJM0cB3yGf25AXHK9ymLTHzwhfRgX6L/Exh7XaV7GfSe26voE+iyL9OM07erfycY7m/nf8eyvN9JLy7THijfbUNbQNqoPFAXAP2vamcMf2Bv1K4NC/NIxrnmbJvsQSdKaDyaaLWz9EACfJT+JUzWlGukKjpc8FR99+oQ5dKWw1KViwW4jb7dxCZ1iRMvUI/9Mzcx5gIQs+24GOTKGjUpwneTDsSkJ6oLu+ZE486ZPUNq/hYFPnT26RgaynPTsr7SJKSWNg5e8uCdfwykIvI75NWhvOJRF4HdEEJin8HSvz1yasOiEa5O4C2NLf9k0GI//ggB1+NCQhOwnDgpxUIGSRjlLC5XyK7edyIKx2WRk1mxyfacGNtxDlGUv5Ny+eJDCwVHGFNyM3XIPF+L8tKAkKOCs+LwWaTZ8L+6AJck9NUaMPxvGk=}
